[project]
name = "layeroptics"
version = "0.1.0"
description = "Anisotropic thin-layer optics and magneto-optics calculator based on Berreman's 4x4 formalism"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
